### ISSUE TITLE
Add 480 x 128 support

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_RA8875#11]
https://forums.adafruit.com/viewtopic.php?f=8&t=109926

**Comment by makermelissa** [comment]
Got a display in the mail today. :)

**Comment by makermelissa** [comment]
Needs a little fine tuning, but so far I have output that looks great. There's just a very high-pitched whine coming from it.

**Comment by ladyada** [comment]
yeah could be the backlight boost circuit

**Comment by makermelissa** [comment]
Yeah, I'll go through the init parameters and adjust them. I just copied the 480x272 init params and tried loading that with no optimization.
