### ISSUE TITLE
Go through all outstanding Pull Requests

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_RA8875#19]
There's a bunch of good PRs out there that need to be pulled in. However, they range from 2-5 years old and some newer merge requests have already been merged in, so some the code changes are a little outdated and should probably be rebased. 

@ladyada, how would you like me to approach these? Because of their age, I could go through each one and reimplement and test with the updated code just to make sure they work. Or should I request the original authors to update these? Thanks.

**Comment by ladyada** [comment]
yeah if they're old and wont merge cleanly, please 'hand merge' to test :)

**Comment by makermelissa** [comment]
Thanks

**Comment by makermelissa** [comment]
@ladyada, while going through the last PR, I noticed there is no setRotation function, nor were any parameters added to the functions. I was going to add some of that functionality myself, but then realized that it would break with certain functions like the drawPixels function I wrote since that relies on memory layout being a certain way for speed. What do you think about that last one? Thanks

**Comment by ladyada** [comment]
i think rotation is worth adding if we can, is it possible to change the RAM incrementer for drawpixels so we can write data in a stream (like we do for the SPI TFT)

**Comment by makermelissa** [comment]
Ok, sounds good. I will continue.

**Comment by makermelissa** [comment]
Thanks for your encouragement @ladyada. I found a bug in the bmp_fast example and fixed that and now have 180 degree rotation in all the drawing functions.
