### ISSUE TITLE
pushPixels Results in Blank Screen

### ISSUE THREAD

**Issue by 9ae8sdf76** [adafruit/Adafruit_RA8875#38]
- Arduino board:  HiLetgo ESP-WROOM-32 ESP32 + Adafruit RA8875 (1590) + Adafruit 7" TFT w/Touchscreen (2354)

- Arduino IDE version (found in Arduino -> About Arduino menu):  CLion 2021.3

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

https://github.com/9ae8sdf76/dbuddy/blob/master/src/esp32dev.cpp#L58 - rename `drawPixels` to `pushPixels`. 

[I reached out on the forums](https://forums.adafruit.com/viewtopic.php?f=19&t=174555&p=850715&hilit=ra8875#p850715), but have been overlooked/ignored. I also attempted to get y'alls attention via email, but was ignored there too. So, as a last-ditch effort, I'm reaching out here. I could really use some assistance. Thank you.

**Comment by ladyada** [comment]
hi we cant see the code you're referring to

**Comment by 9ae8sdf76** [comment]
@ladyada I have updated the link. My apologies.

**Comment by ladyada** [comment]
well one sets up addressing and one doesnt. they're not direct replacements.

**Comment by 9ae8sdf76** [comment]
Do you have any examples of using `pushPixels` that I might be able to look over? That may be a naive question, but I am new and trying to learn as I go. :)

**Comment by ladyada** [comment]
all examples we have are in the library

**Comment by 9ae8sdf76** [comment]
What options are there then? When I use `drawPixels()` the screen draws slowly. I have no point of reference for using `pushPixels()` - which touts being hardware accelerated. Am I just stuck with a slow display?

**Comment by ladyada** [comment]
you could try adjusting the code but i dont see how you could get it any faster. the display just isnt that fast since its going thru a mediated board. thers' some shape acceleration on thea ra8875
as this isnt a bug report, closing
