### ISSUE TITLE
800x480 PLLinit

### ISSUE THREAD

**Issue by cbxbiker61** [adafruit/Adafruit_RA8875#9]
It seems that there is a copy/paste error in PLLinit in the 800x480 section.  From the application note pdf page 7, they are initializing RA8875_PLLC1(0x88) with 0x0B, which in the case of Adafruit_RA8875.cpp should be decimal 11 .

 --- ./Adafruit_RA8875.cpp.orig 2015-07-22 13:45:57.885695858 -0600
+++ ./Adafruit_RA8875.cpp   2015-10-13 22:21:50.869268570 -0600
@@ -116,7 +116,7 @@ void Adafruit_RA8875::PLLinit(void) {
     delay(1);
   }
   if (_size == RA8875_800x480) {
-    writeReg(RA8875_PLLC1, RA8875_PLLC1_PLLDIV1 + 10);
-    writeReg(RA8875_PLLC1, RA8875_PLLC1_PLLDIV1 + 11);
   delay(1);
   writeReg(RA8875_PLLC2, RA8875_PLLC2_DIV4);
   delay(1);

**Comment by makermelissa** [comment]
This seems appropriate. I actually had calculated it when making the CircuitPython driver and ended up using 11 which worked better. I think there were fewer SPI issues with that value.
